/**
 * Build the host entry: lib/index.js (ESM named exports wrapping the
 * authoritative dynamic-plugin body in src/host/index.js).
 *
 * The dynamic body is `return { inject, apply(ctx) { ... } }` with free
 * `harness` (host RPC). Package-form adaptations:
 *   1. `harness.handle(` -> `rpc.handle(` (lexical rewrite); handlers are
 *      registered on the plugin fiber.
 *   2. A same-origin JSON-RPC bridge is exposed over the DSH web server at
 *      /dsh-openwiki/rpc (WebRoute 'exact'), guarded by the
 *      `x-dsh-openwiki: 1` header (cross-origin fetches cannot set it without
 *      a CORS preflight this server does not answer).
 *   3. The `openwiki` settings namespace is registered when
 *      @deepseek-ai/schemastery and the settings service are available
 *      (registration is fiber-bound, no manual disposal).
 *   4. `webServer` is a hard inject: a dependency-free plugin can apply
 *      before the web server row and then miss the service (observed in
 *      the first real boot — route absent).
 *   5. Boot diagnostics are written to $DSH_HOME/openwiki-boot.json so a
 *      restart can be verified without browser access.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = readFileSync(join(root, 'src', 'host', 'index.js'), 'utf8')

// Strip the leading JSDoc header, then the dynamic "return { ... }" wrapper.
const body = src
  .replace(/^\/\*\*[\s\S]*?\*\/\s*/u, '')
  .replace(/^return\s*\{/u, '{')
  .replace(/\}\s*$/u, '}')
  .replace(/\bharness\.handle\(/gu, 'rpc.handle(')

const out = `/**
 * dsh-openwiki host entry (generated by scripts/build-host.mjs from
 * src/host/index.js; do not edit directly).
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'

const plugin = ${body}

export const name = 'dsh-openwiki'
// Hard-depend on the web server and the settings service so cordis activates
// them before this plugin's apply runs (the RPC route registers into the
// former, the settings namespace into the latter); a dependency-free plugin
// can apply first and miss both services.
export const inject = [...(plugin.inject ?? []), 'webServer', 'settings']

const RPC_HEADER = 'x-dsh-openwiki'

// Module-scope handler registry + rpc surface: the plugin body's apply()
// closure references rpc lexically, so it must live at module scope.
const handlers = new Map()
const rpc = {
  handle(method, handler) {
    handlers.set(method, handler)
  },
}

function writeBootDiagnostics(info) {
  try {
    const dir = process.env.DSH_HOME || join(homedir(), '.dsh')
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'openwiki-boot.json'), JSON.stringify({ ts: new Date().toISOString(), ...info }, null, 2), 'utf8')
  } catch (err) {
    console.error('dsh-openwiki: boot diagnostics write failed', String(err && err.message ? err.message : err))
  }
}

export async function apply(ctx) {
  ctx.effect(() => () => { handlers.clear() }, 'dsh-openwiki rpc')
  const diag = { applyStarted: true, webServerPresent: false, routeResult: 'skipped', settingsResult: 'skipped', bodyApply: 'pending' }

  const webServer = ctx.get('webServer')
  diag.webServerPresent = webServer !== undefined
  if (webServer !== undefined) {
    try {
      const stop = webServer.register({
        kind: 'exact',
        path: '/dsh-openwiki/rpc',
        handler: async (req, res) => {
          if (req.headers[RPC_HEADER] !== '1') {
            res.writeHead(403, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: 'forbidden' }))
            return
          }
          let raw = ''
          for await (const chunk of req) raw += chunk
          let payload
          try {
            payload = JSON.parse(raw || '{}')
          } catch {
            res.writeHead(400, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: 'bad json' }))
            return
          }
          const handler = handlers.get(String(payload.method ?? ''))
          if (handler === undefined) {
            res.writeHead(404, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: 'unknown method' }))
            return
          }
          try {
            const result = await handler(payload.args ?? {})
            res.writeHead(200, { 'content-type': 'application/json' })
            res.end(JSON.stringify(result === undefined ? null : result))
          } catch (err) {
            res.writeHead(500, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: String(err && err.message ? err.message : err) }))
          }
        },
      })
      ctx.effect(() => stop, 'dsh-openwiki rpc route')
      diag.routeResult = 'registered'
    } catch (err) {
      diag.routeResult = 'error: ' + String(err && err.message ? err.message : err)
      console.error('dsh-openwiki: rpc route register failed', diag.routeResult)
    }
  } else {
    diag.routeResult = 'skipped: webServer undefined at apply'
    console.error('dsh-openwiki: webServer unavailable; package RPC bridge disabled')
  }

  const settings = ctx.get('settings')
  if (settings !== undefined) {
    try {
      const mod = await import('@deepseek-ai/schemastery')
      const z = mod.default ?? mod
      settings.register('openwiki', z.object({
        autoStart: z.boolean().default(true),
        modelMode: z.union([z.const('follow'), z.const('manual')]).default('follow'),
        defaultLanguage: z.string().default('zh'),
        autoUpdate: z.boolean().default(false),
        autoExport: z.boolean().default(true),
        reference: z.boolean().default(true),
        telemetryDisabled: z.boolean().default(true),
      }), {})
      diag.settingsResult = 'registered'
      console.log('dsh-openwiki: settings namespace registered')
    } catch (err) {
      diag.settingsResult = 'skipped: ' + String(err && err.message ? err.message : err)
      console.error('dsh-openwiki: settings namespace skipped', diag.settingsResult)
    }
  }

  try {
    const result = plugin.apply(ctx)
    diag.bodyApply = 'returned'
    return result
  } catch (err) {
    diag.bodyApply = 'error: ' + String(err && err.message ? err.message : err)
    console.error('dsh-openwiki: body apply failed', diag.bodyApply)
    throw err
  } finally {
    writeBootDiagnostics(diag)
  }
}
`
mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib', 'index.js'), out, 'utf8')
console.log('built lib/index.js')
